// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAALeZ11Vs8OtU0z7y1cY0Yc1S8pId_zco',
    appId: '1:139747610592:web:eb9a64606869afe21fe585',
    messagingSenderId: '139747610592',
    projectId: 'whatsapp-clone-agora-firebase',
    authDomain: 'whatsapp-clone-agora-firebase.firebaseapp.com',
    storageBucket: 'whatsapp-clone-agora-firebase.appspot.com',
    measurementId: 'G-0LKTTCFVRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0EV-kelFxAKQ5UdEPH0ifY24vNI5z-fA',
    appId: '1:139747610592:android:dd0dc15d8a67b48b1fe585',
    messagingSenderId: '139747610592',
    projectId: 'whatsapp-clone-agora-firebase',
    storageBucket: 'whatsapp-clone-agora-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-vbYylqyW4jHnfJ_ShPCxg8PjA0IGx88',
    appId: '1:139747610592:ios:191d656554db1bba1fe585',
    messagingSenderId: '139747610592',
    projectId: 'whatsapp-clone-agora-firebase',
    storageBucket: 'whatsapp-clone-agora-firebase.appspot.com',
    iosClientId: '139747610592-ui751iaiqahe4ggn57a4lcnelcim9mdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappCloneAgoraFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-vbYylqyW4jHnfJ_ShPCxg8PjA0IGx88',
    appId: '1:139747610592:ios:191d656554db1bba1fe585',
    messagingSenderId: '139747610592',
    projectId: 'whatsapp-clone-agora-firebase',
    storageBucket: 'whatsapp-clone-agora-firebase.appspot.com',
    iosClientId: '139747610592-ui751iaiqahe4ggn57a4lcnelcim9mdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappCloneAgoraFirebase',
  );
}
